fix: pass httpProxy agent to node-fetch.
aws-amplify/amplify-cli pull request #10620
Opened 2022-06-17 01:32 UTC by tamutamu

#### Description of changes
In amplify-provider-awscloudformation, pass proxyAgent to `fetch()`.

#### Issue #, if available
#8536

#### Description of how you validated changes

- yarn test, then `amplify-provider-awscloudformation:test` is passed.
- In  behind a proxy, set HTTP_PROXY variable and `amplify pull --appId xxxxxx --envName dev`
- I don't set HTTP_PROXY variable and `amplify pull --appId xxxxxx --envName dev`

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-17 17:33 UTC, ammarkarachi approved these changes

2022-06-27 16:50 UTC, danielleadams commented
Hi @tamutamu - thanks for the contribution! Is there a test that you could add to confirm this works as expected? Thank you.

2022-06-27 16:51 UTC, danielleadams requested changes
Hi @tamutamu - thanks for the contribution! Is there a test that you could add to confirm this works as expected? Thank you.

2022-06-29 06:07 UTC, tamutamu commented
> Hi @tamutamu - thanks for the contribution! Is there a test that you could add to confirm this works as expected? Thank you.

Sorry, I couldn't have wrote any valuable test code for this fix.
In behind a proxy and non proxy, I manually tested.

2022-07-11 05:24 UTC, tamutamu commented
Could you inform me of the current status?
 If you have any questions or concerns, please let me know.

2022-07-13 18:15 UTC, danielleadams approved these changes

2022-07-13 18:16 UTC, danielleadams commented
@timngyn approved - just running our test suite on it now.

2022-07-22 16:39 UTC, danielleadams commented
@timngyn Not sure what happened, but these never ran so starting them now. Thanks for your patience!

2022-07-22 21:05 UTC, danielleadams commented
Added `do-not-merge` tag since this has 2 approvals, but needs to be rebased.

2022-07-23 00:24 UTC, tamutamu commented
@danielleadams 
Thanks. I rebased on `dev` branch(master branch is missing.)

2022-07-27 15:23 UTC, merged