chore: fix publish scripts and verdaccio config
aws-amplify/amplify-cli pull request #10860
Opened 2022-08-08 22:12 UTC by edwardfoyle

#### Description of changes

Fixes a few different release script issues:
1. adds an if statement in the tagged release script to publish to @latest when publishing locally to verdaccio and publish to @<tag> when publishing to npm
2. uses `git checkout` instead of `git switch` where applicable because the git version in CCI does not support `switch`
3. Updates the verdaccio config to not allow proxying `@aws-amplify/cli-internal` to npm. This is a safety measure against installing an unexpected version of the CLI when packaging the binaries
4. A few tweaks to the publish scripts that run locally. The main change is fixing the exit code handling logic around merges that cannot be completed automatically

#### Issue #, if available

#### Description of how you validated changes
local release scripts were tested as much as possible locally.
Doing an e2e run here to make sure verdaccio publish / pkg builds are still working: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/10159/workflows/6e22d581-870a-48e0-933e-a319fd2de87b
#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-09 19:21 UTC, lazpavel commented
`build_pkg_binaries` step failed with some encoding issue `An unexpected error occurred: "http://localhost:4873/@aws-amplify%2fcli-internal: no such package available`

2022-08-09 19:28 UTC, lazpavel requested changes
LGTM after the e2e pipeline is fixed

2022-08-10 17:44 UTC, lazpavel approved these changes

2022-08-10 17:56 UTC, jhockett approved these changes

2022-08-10 18:04 UTC, merged