Add parallelism to e2e suite
aws-amplify/amplify-cli pull request #11080
Opened 2022-09-28 18:20 UTC by awsluja

#### Description of changes
Currently the e2e test suite takes over 3 hours to run.
We have some individual tests suites containing more than 6 tests each, so I've updated the split tests script to allow parallelism on each test job. This should save us several hours each week of waiting for e2e tests to complete; potentially thousands of hours a year.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-03 18:11 UTC, evcodes commented
I know that the previous names for the files were auth5 or whatever, but is there a better name for these tests?

2022-10-03 18:20 UTC, lazpavel submitted a review, later dismissed
changes LGTM, can we trigger the cloud-e2e on this?

2022-10-03 19:20 UTC, awsluja commented
> I know that the previous names for the files were auth5 or whatever, but is there a better name for these tests?
I went with this structure so that it was easier to review initially; as it might be hard to track down the changes if I renamed all the files depending on the test

2022-10-03 19:25 UTC, sobolk commented
> > I know that the previous names for the files were auth5 or whatever, but is there a better name for these tests?
> > I went with this structure so that it was easier to review initially; as it might be hard to track down the changes if I renamed all the files depending on the test

I think numerical suffix is fine if there's no logical grouping and we just load balance.
However `auth_5X` could be called `auth_headless_X`. So there's some room to go after those tests and get better naming.
Also sharding test cases should follow some pattern and should have only one level of nesting. I.e. `5a`, `5b` etc isn't good.

2022-10-03 21:08 UTC, awsluja commented
> > > I know that the previous names for the files were auth5 or whatever, but is there a better name for these tests?
> > > I went with this structure so that it was easier to review initially; as it might be hard to track down the changes if I renamed all the files depending on the test
> 
> I think numerical suffix is fine if there's no logical grouping and we just load balance. However `auth_5X` could be called `auth_headless_X`. So there's some room to go after those tests and get better naming. Also sharding test cases should follow some pattern and should have only one level of nesting. I.e. `5a`, `5b` etc isn't good.

Those are all good points; I would recommend as a follow up PR, since a pure file renaming PR will be much easier to review than a rename+refactor PR

2022-10-04 03:20 UTC, awsluja commented
> changes LGTM, can we trigger the cloud-e2e on this?

Done, I've added a link: https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/11279/workflows/dadbb35c-1491-4f56-a82d-2c070385b880

2022-10-04 17:22 UTC, evcodes requested changes
small notes that I believe existed before your PR. If you can take a look at those that would be awesome!

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-11-b.test.ts
> +  });
only one test, don't need these before/after each

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-11-c.test.ts
> +
same here

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-5a.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-5b.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-5c.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-5d.test.ts
> +  });
""

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-9-b.test.ts
> +
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-6d.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-6c.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-auth-9-c.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-model-a.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-e2e-tests/src/__tests__/schema-model-b.test.ts
> +  });
same

2022-10-04 17:22 UTC, evcodes commented on packages/amplify-migration-tests/src/__tests__/migration_tests/overrides/api-migration-a.test.ts
> +  });
just one test here too...

2022-10-04 19:10 UTC, awsluja commented on packages/amplify-e2e-tests/src/__tests__/global_sandbox-c.test.ts
> +  });
it was skipped before; I was curious, but shouldn't block this pr

2022-10-04 19:10 UTC, awsluja commented on packages/amplify-e2e-tests/src/__tests__/export-pull-d.test.ts
> +  }, true);
follow up with a refactor PR separately as prioritized

2022-10-05 18:52 UTC, evcodes commented
I'd approve all these changes with the small fixes to be implemented in a separate PR

2022-10-05 18:52 UTC, evcodes approved these changes

2022-10-05 23:42 UTC, lazpavel approved these changes

2022-10-05 23:46 UTC, merged