chore: remove unnecessary fields from bug template
aws-amplify/amplify-cli pull request #11121
Opened 2022-10-05 21:51 UTC by josefaidt

#### Description of changes

When triaging issues, some of the fields do not provide much value for diagnosis, and instead can become a hurdle to filing issues. We can help narrow the focus and reduce the time of filing the report by removing the following fields:

- removes section for Amplify Commands
- removes section for Amplify Categories
- removes section for GraphQL Schema (this no longer applies to the CLI repo)

I have also considered removing the checklist at the beginning of the document in favor of one of the following:

- remove entirely
- move to the end of the document (to align with wording of checklist heading, "Before submitting...")
- remove in favor of noting the following at the top of the document
	```md
	Be sure to read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports)
	```
  and add a condensed checklist at the end of the document
	```gfm
    - [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
    - [X] I have removed any sensitive information from my code snippets and submission.
	```

With the checklist at the beginning of the document its contents may be glossed over in order to dive into the details of the issue experienced. Moving the checklist to the end of the document serves as a final checklist before submitting where it may be more meaningful

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-07 15:31 UTC, evcodes submitted a review, later dismissed

2022-10-07 15:32 UTC, evcodes commented
thanks for improving the developer experience of our contributors!

2022-10-07 16:04 UTC, sobolk submitted a review, later dismissed

2022-10-10 17:17 UTC, ykethan commented
Providing common troubleshooting documentation links that can be added to issue template:
CLI/GraphQL: https://docs.amplify.aws/cli/project/troubleshooting/
GraphQL: https://docs.amplify.aws/cli/graphql/troubleshooting/#backfill-opensearch-index-from-dynamodb-table

2022-10-11 17:31 UTC, edwardfoyle commented on .github/ISSUE_TEMPLATE/1.bug_report.yaml
> +        For issues regarding REST API's, GraphQL API's, or containers, please visit https://github.com/aws-amplify/amplify-category-api/issues
should we link straight to the new issue page here instead of the issues list?

2022-10-11 17:31 UTC, edwardfoyle commented on .github/ISSUE_TEMPLATE/1.bug_report.yaml
> -        > For **Amplify Codegen** issues, go [here](https://github.com/aws-amplify/amplify-codegen/issues/new/choose).
Seems like we might want to keep these links in?

2022-10-12 14:04 UTC, josefaidt commented
I did not mean to start a review 😵

2022-11-21 22:49 UTC, jhockett approved these changes

2022-11-22 15:58 UTC, evcodes commented on .github/ISSUE_TEMPLATE/1.bug_report.yaml
> +      description: "For example: npm, yarn, curl, etc."
are we going with single quotes or double quotes?

2022-11-22 15:59 UTC, evcodes commented on .github/ISSUE_TEMPLATE/1.bug_report.yaml
> +      description: "For example: Mac, Windows, Ubuntu."
same question here

2022-11-22 15:59 UTC, evcodes requested changes
small nit

2022-12-06 18:09 UTC, evcodes approved these changes
Awesome, LGTM

2022-12-06 22:49 UTC, edwardfoyle approved these changes

2022-12-06 22:50 UTC, merged