chore: reclassify common sdk errors
aws-amplify/amplify-cli pull request #12459
Opened 2023-04-12 23:21 UTC by goldbez

#### Description of changes
This PR takes common SDK faults and reclassifies them as AmplifyErrors. See the table below for the current mapping.

Origional Fault | New Error
-|-
The provided token has expired. | Your AWS access tokens have expired.; Please refresh your tokens.
The AWS Access Key Id you provided does not exist in our records. | Your AWS tokens are invalid.; Please refresh your tokens.
The request signature we calculated does not match the signature you provided. | Your AWS tokens are invalid.; Please refresh your tokens.
The provided token is malformed or otherwise invalid. | Your AWS tokens are invalid.; Please refresh your tokens.
...is not authorized to perform... | Please update the permissions.
Rate Exceeded | Please try again.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-13 14:18 UTC, edwardfoyle commented on packages/amplify-cli/src/amplify-exception-handler.ts
> +    resolution: 'Please refresh your tokens.',
Nit: remove the "please" from all of these resolutions. For the refresh tokens error, maybe change to "Refresh your AWS credentials and retry the operation"

2023-04-13 14:19 UTC, edwardfoyle commented on packages/amplify-cli/src/amplify-exception-handler.ts
> +    resolution: 'Please update the permissions.',
will there be any output that gives the customer an idea about what permissions they should add? Is there an Amplify or AWS docs page we can link to about how to add permissions to a User/Role?

2023-04-13 14:21 UTC, edwardfoyle commented on packages/amplify-cli/src/amplify-exception-handler.ts
> +    resolution: 'Please try again.',
```suggestion
    resolution: 'Try the operation again. If the problem persists, check or increase your service quotas at https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html',
```

2023-04-13 14:22 UTC, edwardfoyle commented on packages/amplify-cli/src/amplify-exception-handler.ts
> +  resolution: string;
should this just be an instance of an AmplifyError instead of the inputs to an AmplifyError?

2023-04-13 14:23 UTC, edwardfoyle commented on packages/amplify-cli/src/amplify-exception-handler.ts
> +  if (err.options?.message) {
nit: negate this condition and early return instead of nesting the whole function in the if

2023-04-13 14:35 UTC, Amplifiyer requested changes
Ideally, we would like to catch/convert such errors at source, i.e. where the aws-sdk calls are happening. This approach 'a catch-all` does not scale well. Currently the only conversions we are doing here are for node errors which slipped through our usual try/catch.

2023-04-14 22:33 UTC, goldbez commented
Closing in favor of localizing error handeling.

2023-04-14 22:33 UTC, closed without merging