fix(amplify-console-hosting): add missing proxy support
aws-amplify/amplify-cli pull request #12510
Opened 2023-04-20 18:18 UTC by jhockett

#### Description of changes
Honor proxy settings for `amplify publish`

#### Issue #, if available
Fixes https://github.com/aws-amplify/amplify-cli/issues/12460

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [x] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-26 17:12 UTC, danielleadams requested changes
@jhockett is there a way to test this?

2023-07-31 17:06 UTC, ykethan commented
Test this by setting up a ubuntu EC2 instance and [tiny proxy](http://tinyproxy.github.io/).
with security groups and tiny config file setup to allow my ip address and ports.

setup env variables as provided here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html in the local terminal. do not forget the no proxy env 
created a new app with hosting and tested publish.

on sucessfull publish 
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/74f215e9-512c-4f9e-b2c8-b126a00a9488)

when we dont allow a user ip for example: 
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/90a55bbc-77a2-4e0d-93d8-ec71b60fa0c7)

also will obeserve
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/674afe19-00d9-4eeb-bb68-adf36c14fba0)

2023-08-01 16:09 UTC, sobolk approved these changes

2023-08-01 17:15 UTC, awsluja commented on packages/amplify-console-hosting/src/utils/amplify-console-utils.js
> +  const proxyOption = proxy ? { agent: new ProxyAgent(proxy) } : {};
see https://github.com/aws-amplify/amplify-cli/pull/13012

2023-08-01 17:18 UTC, awsluja requested changes
looks like you have pulled in ^6.3.0 version but need to update invocations of the constructor

2023-08-01 17:32 UTC, jhockett commented on packages/amplify-console-hosting/src/utils/amplify-console-utils.js
> +  const proxyOption = proxy ? { agent: new ProxyAgent(proxy) } : {};
Updated.

2023-08-01 18:33 UTC, awsluja submitted a review, later dismissed

2023-08-01 19:26 UTC, sobolk approved these changes

2023-08-01 19:26 UTC, sobolk commented on packages/amplify-console-hosting/src/utils/amplify-console-utils.js
> +  const proxyOption = proxy ? { agent: new ProxyAgent() } : {};
can you copy comment from other places like this that explains why we're not consuming `proxy` ?

2023-08-01 19:53 UTC, sobolk approved these changes

2023-08-01 19:59 UTC, awsluja approved these changes

2023-08-01 20:46 UTC, merged