DRAFT: release pipelines configurations
aws-amplify/amplify-cli pull request #12570
Opened 2023-05-02 18:28 UTC by awsluja

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-18 20:25 UTC, sdstolworthy requested changes

2023-05-18 20:25 UTC, sdstolworthy commented on shared-scripts.sh
> +    ./out/amplify-pkg-linux-x64 --version
This is probably debug code? Does this need to be here?

2023-05-18 20:25 UTC, sdstolworthy commented on codebuild_specs/release_workflows/hotfix_workflow.yml
> +    TEST_SUITE: src/__tests__/auth_2b.test.ts
Do all the `TEST_SUITE` vars need to be removed?

2023-06-12 19:14 UTC, sobolk commented
Please incorporate publish.sh script split, see for reference https://github.com/aws-amplify/amplify-cli/pull/12775 .

2023-07-07 22:26 UTC, awsluja commented
Closing in favor of: https://github.com/aws-amplify/amplify-cli/pull/12918

2023-07-07 22:26 UTC, closed without merging