chore: remove opensearch mock e2e test
aws-amplify/amplify-cli pull request #12960
Opened 2023-07-17 21:47 UTC by goldbez

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-17 22:03 UTC, awsluja approved these changes

2023-07-18 17:32 UTC, sobolk commented on packages/amplify-util-mock/package.json
>      ]
are we loosing coverage ?

2023-07-18 18:34 UTC, sobolk requested changes
In order to move forward we should:
- find a way to keep this working on CCI, locally
- have a root cause analysis, i.e. know to some level of detail why this test is failing
- plan to bring this back or good justification why this can be dropped forever.

2023-08-17 18:20 UTC, closed without merging

2023-08-17 18:20 UTC, jhockett commented
Closing this PR since the tests were fixed by https://github.com/aws-amplify/amplify-cli/pull/13031