fix(amplify-frontend-javascript): use CommonJS exports to support Node env
aws-amplify/amplify-cli pull request #13174
Opened 2023-08-31 00:33 UTC by HuiSF

#### Description of changes

Changed the template of `aws-exports.js` file for `amplify-front-javascript` package to use CommonJS exports. This allows to import and use `aws-exports.js` in a Node environment without transpiling ES modules.

This change is required to allow consuming the `aws-exports` in Next.js `next.config.js`.

#### Issue #, if available

#### Description of how you validated changes

* `yarn setup-dev` and regenerated `aws-exports.js` file and run sample app locally

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-31 00:35 UTC, cshfang approved these changes

2023-08-31 14:52 UTC, edwardfoyle reviewed
Is there any risk here to customers who are currently importing the `aws-exports.js` file in an ES6 module?

2023-08-31 14:59 UTC, sobolk requested changes
Please add automated test coverage that verifies that this work for both CommonJS and ES6 projects.

You can find some inspiration by looking at how do we create react apps in e2e tests.
However, I think this can be solved by integration test of some sort that doesn't require aws account.

2023-09-12 11:49 UTC, bombguy commented
cherry-picked @HuiSF 's change and added e2e test in this PR: https://github.com/aws-amplify/amplify-cli/pull/13213

2023-09-21 15:36 UTC, closed without merging