update readme with gen 2 GA messaging
aws-amplify/amplify-cli pull request #13755
Opened 2024-05-01 20:55 UTC by edwardfoyle

Update readme with gen 2 GA wording

2024-05-01 21:06 UTC, swaminator requested changes

2024-05-01 21:06 UTC, swaminator commented on Readme.md
> +> For Gen 1 customers, we are actively developing migration tooling to aid in transitioning your project from Gen 1 to Gen 2. Until then, we recommend you continue working with your Gen 1 Amplify pro
If you are an existing Gen 1 customer, we recommend that you continue working with your Gen 1 Amplify project. We are actively developing migration tooling to aid in transitioning your project from Gen 1 to Gen 2.  We remain committed to supporting both Gen 1 and Gen 2 for the foreseeable future.

2024-05-01 21:39 UTC, edwardfoyle commented on Readme.md
> +> For Gen 1 customers, we are actively developing migration tooling to aid in transitioning your project from Gen 1 to Gen 2. Until then, we recommend you continue working with your Gen 1 Amplify pro
```suggestion
> If you are an existing Gen 1 customer, we recommend that you continue working with your Gen 1 Amplify project. We are actively developing migration tooling to aid in transitioning your project from Gen 1 to Gen 2. We remain committed to supporting both Gen 1 and Gen 2 for the foreseeable future.
```

2024-05-01 21:43 UTC, swaminator requested changes
One more nit that I missed last time.

2024-05-01 21:43 UTC, swaminator commented on Readme.md
> +> # Amplify Gen 2 is now available
Amplify Gen 2 is now generally available

2024-05-06 16:37 UTC, 0618 submitted a review, later dismissed

2024-05-06 16:39 UTC, Amplifiyer approved these changes

2024-05-06 16:48 UTC, swaminator approved these changes

2024-05-06 18:50 UTC, sobolk approved these changes

2024-05-06 21:45 UTC, merged