fix: update default file permissions for credentials/config
aws-amplify/amplify-cli pull request #5246
Opened 2020-09-03 20:41 UTC by jhockett

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-04 00:26 UTC, attilah requested changes
Added comments about naming the methods, for `pathManager` I'd like to see it, the other is for easier readibility.

2020-09-04 00:26 UTC, attilah commented on packages/amplify-cli-core/src/state-manager/pathManager.ts
> +  getCredentialsFilePath = (): string => path.normalize(path.join(this.getDotAWSDirPath(), PathConstants.Credentials));
can we call these `getAWS*` methods as `getConfigFilePath` is way to generic even for the CLI.

2020-09-04 00:26 UTC, attilah commented on packages/amplify-cli/src/index.ts
> +function verifyFilePermissions(filePath) {
`ensureFilePermissions` probably a better name since we also changing it, not just verifying.

2020-09-08 19:29 UTC, attilah approved these changes

2020-09-09 17:05 UTC, UnleashedMind approved these changes

2020-09-09 17:28 UTC, merged