fix: add owner field if owner auth is included in auth rules
aws-amplify/amplify-cli pull request #5335
Opened 2020-09-15 17:23 UTC by zeynepsu

*Issue #, if available:*
https://github.com/aws-amplify/amplify-js/issues/5687

*Description of changes:*
Add owner field to generated schema if it does not exist in the original schema but owner auth is included in auth rules.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-15 18:28 UTC, yuth requested changes

2020-09-15 18:28 UTC, yuth commented on packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts
> +      if ("owner" === this.getFieldName(field) && "String" === this.getNativeType(field)) {
The field name that stores owner value can be changed with `ownerField` in auth directive. Model gen should support overriding this
```gql
type Post
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownedBy", operations: [create, update, delete, read] },
    ])
{
  id: ID!
  title: String!
  # ownedBy: String would be automatically added
}
```
You can find the definition of `auth` directive here
https://docs.amplify.aws/cli/graphql-transformer/directives#definition-2

2020-09-15 21:49 UTC, yuth reviewed
Realized that this would not work without corresponding change in the graphql transformer to expose the owner fields. Without that, the owner information will be available only in the DynamoDB and only accessible to resolvers, but will not be exposed in type.

2020-09-15 21:51 UTC, yuth commented on packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts
> +          }
`@auth` directive supports multiple owner rules, for instance this is an valid auth rule
```gql
type Todo
@model
@auth(
  rules: [
    { allow: owner, ownerField: "ownedBy" }
    { allow: owner, ownerField: "owner" }
  ]
) {
  id: ID!
  name: String!
  description: String
}
```

2020-09-17 16:50 UTC, iartemiev requested changes
This also requires changes to `amplify-codegen/src/commands/models.js` in order to add the owner field into schema.js that gets generated when calling `amplify codegen models`

2020-09-18 22:15 UTC, yuth requested changes

2020-09-18 22:15 UTC, yuth commented on packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts
> +export function getOwnerFieldName(rule: any): string | undefined {
Can you define type for `rule` instead of `any`

2020-09-18 22:15 UTC, yuth commented on packages/amplify-codegen-appsync-model-plugin/src/visitors/appsync-typescript-visitor.ts
> +    }
```suggestion
    let ownerAuthRules = getOwnerAuthRules(modelObj);
    if (ownerAuthRules !== undefined) {
      for (let rule of ownerAuthRules) {
        let ownerFieldName = getOwnerFieldName(rule);
        if (ownerFieldName !== undefined && !hasOwnerField(modelObj.fields, ownerFieldName)) {
          modelDeclarations.addProperty(ownerFieldName, "String", undefined, 'DEFAULT', {
            readonly: true,
            optional: true,
          });
         }
      }
    }
```

2020-09-21 14:41 UTC, iartemiev commented
Working as expected with a simple owner auth schema:
```graphql
type Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
}
```
However, subscriptions are failing with multiple owner auth rules, e.g.
```graphql
type Post
@model
@auth(
  rules: [
    { allow: owner, ownerField: "owner" }
    { allow: owner, ownerField: "editors" }
  ]
) {
  id: ID!
  title: String!
  owner: String
  editors: [String]
}

```
They're failing with the current CLI release as well though (not just this PR). @yuth when you have a moment, let's discuss what we're expecting the generated subscriptions to look like for the 2nd schema. Maybe the bug for this is on the library side.

2020-09-22 13:50 UTC, iartemiev approved these changes
From the library side: I'm good with us merging this. 
The issue with multiple ownerFields I mentioned in my previous comment is outside the scope of this PR, so we can address it later

2020-09-22 16:59 UTC, yuth approved these changes

2020-09-23 17:25 UTC, merged