fix(cli): fixed projName and envName
aws-amplify/amplify-cli pull request #5400
Opened 2020-09-25 00:33 UTC by ammarkarachi

fixes #5399

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-29 03:37 UTC, attilah requested changes
Could you add some e2e tests that verifies the deployed tags to make sure it is working correctly niw?

2020-09-29 03:37 UTC, yuth commented on packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts
> +  return HydrateTags(stateManager.getProjectTags(), envName, projectName);
```suggestion
  return HydrateTags(stateManager.getProjectTags(), { envName, projectName });
```

2020-09-30 19:04 UTC, nikhname approved these changes

2020-09-30 19:38 UTC, attilah approved these changes

2020-09-30 19:51 UTC, yuth approved these changes

2020-09-30 21:05 UTC, merged