fix(amplify-codegen-appsync-model-plugin): add ownerField to modelgen…
aws-amplify/amplify-cli pull request #5455
Opened 2020-09-30 18:01 UTC by AaronZyLee

*Issue #, if available:*
aws-amplify/amplify-js#5687
*Description of changes:*
`amplify codegen models` will generate `ownerField` automatically in implicit cases and will not override the field if it is defined explicitly in the schema. The changes apply to all the SDKs(js, android and ios)
### Sample input
```
 type Post @model @auth(rules: [
  { allow: owner , ownerField: "customOwnerField1"},
  { allow: owner , ownerField: "customOwnerField2"},
  ]) {
   id: ID!
   name: String!
 } 
```
### Sample output for Java
```
/** This is an auto generated class representing the Post type in your schema. */
@SuppressWarnings("all")
@ModelConfig(pluralName = "Posts", authRules = {
  @AuthRule(allow = AuthStrategy.OWNER, ownerField = "customOwnerField1", identityClaim = "cognito:username", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ }),
  @AuthRule(allow = AuthStrategy.OWNER, ownerField = "customOwnerField2", identityClaim = "cognito:username", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
})
public final class Post implements Model {
  public static final QueryField ID = field("id");
  public static final QueryField NAME = field("name");
  public static final QueryField CUSTOM_OWNER_FIELD1 = field("customOwnerField1");
  public static final QueryField CUSTOM_OWNER_FIELD2 = field("customOwnerField2");
  private final @ModelField(targetType="ID", isRequired = true) String id;
  private final @ModelField(targetType="String", isRequired = true) String name;
  private final @ModelField(targetType="String") String customOwnerField1;
  private final @ModelField(targetType="String") String customOwnerField2;
  public String getId() {
      return id;
  }
  
  public String getName() {
      return name;
  }
  
  public String getCustomOwnerField1() {
      return customOwnerField1;
  }
  
  public String getCustomOwnerField2() {
      return customOwnerField2;
  }
//...
//Constructors, getters and builders also get updated. See details in test snapshots.
```
### Sample output for Swift
```
// swiftlint:disable all
import Amplify
import Foundation

extension Post {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case name
    case customOwnerField1
    case customOwnerField2
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let post = Post.keys
    
    model.authRules = [
      rule(allow: .owner, ownerField: "customOwnerField1", identityClaim: "cognito:username", operations: [.create, .update, .delete, .read]),
      rule(allow: .owner, ownerField: "customOwnerField2", identityClaim: "cognito:username", operations: [.create, .update, .delete, .read])
    ]
    
    model.pluralName = "Posts"
    
    model.fields(
      .id(),
      .field(post.name, is: .required, ofType: .string),
      .field(post.customOwnerField1, is: .optional, ofType: .string),
      .field(post.customOwnerField2, is: .optional, ofType: .string)
    )
    }
}
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-30 18:28 UTC, richardmcclellan approved these changes
:shipit:

2020-09-30 21:12 UTC, wooj2 reviewed
in looking at your example, i noticed that your test input is:
```
  { allow: owner , ownerField: "customOwnerField1"},
  { allow: owner , ownerField: "customOwnerField2"},
```
Is this a valid use case?  I have never seen a case where we would have two different custom owner fields.

2020-09-30 21:28 UTC, richardmcclellan commented
> in looking at your example, i noticed that your test input is:
> 
> ```
>   { allow: owner , ownerField: "customOwnerField1"},
>   { allow: owner , ownerField: "customOwnerField2"},
> ```
> 
> Is this a valid use case? I have never seen a case where we would have two different custom owner fields.

[The docs](https://docs.amplify.aws/cli/graphql-transformer/directives#multiple-authorization-rules) describe one such use case where an owner should be able to do perform all operations (create, read, update, delete), but a list of `editors` should only be able to read and update.

2020-09-30 22:05 UTC, wooj2 commented
> > in looking at your example, i noticed that your test input is:
> > ```
> >   { allow: owner , ownerField: "customOwnerField1"},
> >   { allow: owner , ownerField: "customOwnerField2"},
> > ```
> > 
> > 
> > Is this a valid use case? I have never seen a case where we would have two different custom owner fields.
> 
> [The docs](https://docs.amplify.aws/cli/graphql-transformer/directives#multiple-authorization-rules) describe one such use case where an owner should be able to perform all operations (create, read, update, delete), but a list of `editors` should only be able to read and update.

Seems like we should test that case instead?

2020-10-01 13:54 UTC, zeynepsu commented
Should there be a corresponding test for swift visitor as well?

2020-10-01 16:16 UTC, AaronZyLee commented
> > > in looking at your example, i noticed that your test input is:
> > > ```
> > >   { allow: owner , ownerField: "customOwnerField1"},
> > >   { allow: owner , ownerField: "customOwnerField2"},
> > > ```
> > > 
> > > 
> > > Is this a valid use case? I have never seen a case where we would have two different custom owner fields.
> > 
> > 
> > [The docs](https://docs.amplify.aws/cli/graphql-transformer/directives#multiple-authorization-rules) describe one such use case where an owner should be able to perform all operations (create, read, update, delete), but a list of `editors` should only be able to read and update.
> 
> Seems like we should test that case instead?

I include the test cases in the new commit for swift tests.

2020-10-01 17:04 UTC, wooj2 commented on packages/amplify-codegen-appsync-model-plugin/src/utils/process-auth.ts
> -export function getOwnerAuthRules(modelObj: CodeGenModel): AuthRule[] {
I'm not familiar with this code, but it seems like we are removing `getOwnerAuthRules` (and getOwnerFieldName, etc..) from everywhere.  Can anyone verify that this is the right thing to do?

2020-10-01 18:05 UTC, AaronZyLee commented on packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
> +        `;
The temporary solution for missing ownerField type is optional string, which is `String`.

2020-10-01 18:21 UTC, AaronZyLee commented on packages/amplify-codegen-appsync-model-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
> +        `;
I am not sure if these tests are necessary. I think the leaving out variable test is already covered by the test case `it('should add the custom ownerField to model generation automatically if not provided in schema')`, which proves that a missing field will be added with default type.

2020-10-05 17:30 UTC, yuth requested changes
Could you fix the LGTM errors. Other than that it looks good

2020-10-05 17:43 UTC, yuth approved these changes

2020-10-05 17:47 UTC, merged