feat(amplify-frontend-flutter)
aws-amplify/amplify-cli pull request #5849
Opened 2020-11-12 19:01 UTC by haverchuck

*Description of changes:*
Adds developer preview functionality for amplify-flutter projects.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-12 19:46 UTC, renebrandel commented on packages/amplify-cli/scripts/post-install.js
> +console.log(chalk.green('Flutter Getting Started - https://docs.amplify.aws/start/q/integration/flutter'));
Flutter (Developer Preview)

2020-11-12 20:38 UTC, haverchuck commented on packages/amplify-cli/scripts/post-install.js
> +console.log(chalk.green('Flutter Getting Started - https://docs.amplify.aws/start/q/integration/flutter'));
Done!

2020-11-13 16:16 UTC, attilah requested changes
I reviewed the other Flutter PR, those comments should be addressed here then ;-)

2020-11-13 20:27 UTC, haverchuck commented
@attilah I'm assuming you mean this one:  https://github.com/aws-amplify/amplify-cli/pull/5775

2020-11-13 23:28 UTC, attilah commented
@haverchuck yes.

2020-11-17 02:09 UTC, haverchuck commented
@attilah I answerd your inline comments in @AaronZyLee 's  initial PR.  I made several of your requested revisions.

You also had two general comments:

> * Put all the Flutter related E2E tests into 1 test file within the E2E project to make separation easier later and don't spread across categories.
> * Reorg the plugin source code into `src` folder with `lib` output and add TypeScript passthrough compilation, like we have in other some packages like `amplify-provider-awscloudformation` as an example.

Regarding the first bullet, I decided not to do this because none of the other test files appear organzied by platform.  I think it would be better to reorganzie all of them if needed.

Regarding bullet 2 - as we discussed, this would potentially be a breaking change due to the need to upgrade the graphql-config library to version 3.  This upgrade would break our amplify-codegen package, since the new graphql-config libary uses "include/exclude" instead of "includes/excludes".

2020-11-17 23:49 UTC, attilah approved these changes
LGTM, thanks for the changes, as we discussed, I understand the TS concerns, we can address it later for all the packages in 1 go.

2020-11-24 20:05 UTC, merged