fix: validate config after profile selection
aws-amplify/amplify-cli pull request #6567
Opened 2021-02-08 18:28 UTC by nikhname

fix #5777

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-26 20:25 UTC, yuth requested changes
This handles profile validation only in case of init. If the prole is missing then `amplify push` will end up using the default profile. Please update the code to throw errors when the named profile is missing.

2021-03-02 19:43 UTC, attilah requested changes
Update based on comments pleased.

2021-03-02 19:43 UTC, attilah commented on packages/amplify-provider-awscloudformation/src/system-config-manager.js
> +    throw err;
Add `err.stack = undefined;` so we'll not print stacktrace and that's a better DX for customers.

2021-03-06 00:07 UTC, nikhname commented
> This handles profile validation only in case of init. If the prole is missing then `amplify push` will end up using the default profile. Please update the code to throw errors when the named profile is missing.

Is this true? It looks like if the profile is missing altogether we error out at this [line](https://github.com/aws-amplify/amplify-cli/blob/7d7507e593b22921b71382f8d0558fd0b8593300/packages/amplify-provider-awscloudformation/src/system-config-manager.js#L90) in both init and push.

2021-03-19 18:25 UTC, yuth commented
> > This handles profile validation only in case of init. If the prole is missing then `amplify push` will end up using the default profile. Please update the code to throw errors when the named profile is missing.
> 
> Is this true? It looks like if the profile is missing altogether we error out at this [line](https://github.com/aws-amplify/amplify-cli/blob/7d7507e593b22921b71382f8d0558fd0b8593300/packages/amplify-provider-awscloudformation/src/system-config-manager.js#L90) in both init and push.

I still can reproduce this. In am already provisioned project go and change the profile name to 'some-random-which-doesnt-exists` in `amplify/.config/local-aws-info.json` and do an push and it still goes through.

2021-04-09 23:39 UTC, jhockett commented
Closing in favor of https://github.com/aws-amplify/amplify-cli/pull/7017

2021-04-09 23:39 UTC, closed without merging