fix(amplify-util-mock): mock AWS access key when server is running
aws-amplify/amplify-cli pull request #6923
Opened 2021-03-20 05:04 UTC by cjihrig

#### Description of changes
This commit updates function mocking to use the mock AWS access key value when the mock API server is running.

#### Issue #, if available
https://github.com/aws-amplify/amplify-cli/issues/6897

#### Description of how you validated changes
Local testing and unit tests.

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-21 01:21 UTC, ammarkarachi approved these changes

2021-03-22 20:10 UTC, edwardfoyle requested changes
Unless I'm misunderstanding the linked issue, I don't think this solves the problem. The issue is that the `API_<API NAME>_GRAPHQLAPIKEYOUTPUT` env var does not get the fake API key. This is different than the `AWS_ACCESS_KEY_ID` which is modified in this PR. I think what we need is another condition [here](https://github.com/aws-amplify/amplify-cli/blob/dceb13a76a85a05940078868a3e2e1ca85656938/packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts#L64) to check for `attribute === 'GraphQLApiKeyOutput'` and if so, set the val to the mock API key

2021-03-23 00:06 UTC, edwardfoyle commented on packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts
> +          val = 'da2-fakeApiId123456';
If it's not too difficult to move this value to an exported const that is imported when needed that would be nice

2021-03-23 00:06 UTC, edwardfoyle commented on packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts
> +        } else if (attribute === 'GraphQLApiKeyOutput') {
I think this should be
```suggestion
        } else if (attribute === 'GraphQLAPIKeyOutput') {
```

2021-03-23 00:06 UTC, edwardfoyle commented on packages/amplify-util-mock/src/utils/lambda/populate-cfn-params.ts
> +        if (attribute === 'GraphQLAPIEndpointOutput') {
nit might be a bit cleaner to make this a switch statement

2021-03-23 16:15 UTC, edwardfoyle commented on packages/amplify-util-mock/src/api/api.ts
> +export const MOCK_API_KEY = 'da2-fakeApiId123456';
although it's slightly tangental to this PR, this const should be used in the other places where we use this value as well: https://github.com/aws-amplify/amplify-cli/search?q=da2-fakeApiId123456

2021-03-23 16:15 UTC, edwardfoyle approved these changes

2021-03-24 01:08 UTC, merged