fix: show error message when project initalization fail
aws-amplify/amplify-cli pull request #7226
Opened 2021-04-30 23:05 UTC by yuth

#### Description of changes

The CLI throws ugly error if the initialization of project fails when the bucket limit is hit. This change shows list of errors instead of a stack trace
## Old error
```
ROLLBACK_COMPLETE amplify-initfail-dev-160404 AWS::CloudFormation::Stack Fri Apr 30 2021 16:04:20 GMT-0700 (Pacific Daylight Time)
⠏ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
TypeError: Cannot read property 'Stacks' of null
    at processStackCreationData (/Users/yathiraj/.config/yarn/global/node_modules/amplify-provider-awscloudformation/src/initializer.js:108:44)
    at Object.run (/Users/yathiraj/.config/yarn/global/node_modules/amplify-provider-awscloudformation/src/initializer.js:80:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
## New error

```
⠧ Initializing project in the cloud...

Following resources failed

Resource Name: amplify-initfail-dev-155719-unauthRole (AWS::IAM::Role)
Event Type: create
Reason: Resource creation cancelled

Resource Name: amplify-initfail-dev-155719-authRole (AWS::IAM::Role)
Event Type: create
Reason: Resource creation cancelled

Resource Name: DeploymentBucket (AWS::S3::Bucket)
Event Type: create
Reason: You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 9PE5RBXKCAHYN2ZC; S3 Extended Request ID: YXRhl55q/zkp8k23YWOR89/ypoPAE2ZVmMbXGTphHdL63MM1aO/zF1CrR1yi9rkoln29v/8qDuI=; Proxy: null)

✖ Root stack creation failed
``` 

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-30 23:15 UTC, jhockett approved these changes
LGTM

2021-05-01 01:16 UTC, cjihrig approved these changes

2021-05-03 15:25 UTC, cjihrig requested changes
It looks like there is a CI failure. I'm going to mark as changes requested so this doesn't get accidentally merged.

2021-05-03 19:19 UTC, yuth commented
> It looks like there is a CI failure. I'm going to mark as changes requested so this doesn't get accidentally merged.

Tests are passing now

2021-05-04 16:36 UTC, cjihrig approved these changes

2021-05-04 16:36 UTC, cjihrig commented on packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
> +jest.setTimeout(15000);
Is this needed?

2021-05-04 18:07 UTC, yuth commented on packages/amplify-provider-awscloudformation/src/__tests__/system-config-manager.test.ts
> +jest.setTimeout(15000);
Yes. The await otherwise times out

2021-05-04 18:33 UTC, merged