feat(graphql-http-transformer): support ${region} template in @http url
aws-amplify/amplify-cli pull request #7277
Opened 2021-05-06 23:09 UTC by johnpc

#### Description of changes

This commit adds support for a ${region} template, that is replaced with the AWS region of the
environment. It works similarly to the exiting ${env} template which returns the name of the current
amplify environment.

#### Issue #, if available

fix #6520

re https://github.com/aws-amplify/docs/pull/3203

#### Description of how you validated changes

I added unit tests. I also created an app using the feature it generated the expected data source  in AppSync.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-07 14:59 UTC, cjihrig commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +  console.log('JCJC-graphql-http-transformer.ts', value, env, region);
Please remove this.

2021-05-07 15:22 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +  if (referencesRegion(value)) {
should this logic be preferred? That is, should the change also be applied to `packages/graphql-http-transformer/src/resources.ts`?

2021-05-07 15:22 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +function replaceEnv(env: cdk.CfnParameter, region: string, value: string): string {
good call - I've also done the same rename in `packages/graphql-http-transformer/src/resources.ts`

2021-05-07 15:22 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +  if (referencesEnv(value)) {
done

2021-05-07 15:22 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +  console.log('JCJC-graphql-http-transformer.ts', value, env, region);
how embarrassing! consider it gone.

2021-05-07 15:22 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
> +});
correct, that was the intention. I've updated it to reflect that now.

2021-05-07 15:23 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/graphql-http-transformer.ts
> +  if (!vars.env && !vars.region) {
done

2021-05-13 20:05 UTC, cjihrig requested changes

2021-05-13 20:06 UTC, cjihrig commented
This will require an internal API review before we can merge this.

@renebrandel this PR also updates v1 of the GraphQL Transformer. Do you want that?

2021-05-13 21:33 UTC, renebrandel commented
I think this feature makes sense. Let's get a couple of 👍 internally as well. @cjihrig can you port this also to v2 transformer?

2021-05-13 21:36 UTC, cjihrig commented
@renebrandel this PR covers v2 as well 👍

2021-05-13 21:44 UTC, renebrandel commented
awesome! LGTM from my end.

2021-05-14 18:07 UTC, johnpc commented on packages/amplify-graphql-http-transformer/src/__tests__/amplify-graphql-http-transformer.test.ts
> +test('region on the URI path', () => {
done.

2021-05-17 15:32 UTC, cjihrig approved these changes
LGTM pending API review.

2021-05-25 21:07 UTC, johnpc commented
Had an API Review meeting with @edwardfoyle @yuth and Praveen. Changing the template from `${region}` to `${aws_region}`.

2021-06-24 23:19 UTC, merged