feat(amplify-category-auth): enable alternative signup/signin options
aws-amplify/amplify-cli pull request #7461
Opened 2021-06-04 20:17 UTC by johnpc

#### Description of changes

This pull request mirrors the options presented to users when creating a cognito user pool in the aws
console. Alternative sign in options allow developers to create a coginito user that can sign in
using their preferred username, phone number, or email address.

![Screen Shot 2021-06-04 at 4 13 51 PM](https://user-images.githubusercontent.com/4824042/120857914-fea13c80-c54f-11eb-8898-a4d9925db3bd.png)

#### Issue #, if available

#1546

#### Description of how you validated changes

- updated unit tests
- updated e2e tests
- created app, walked through `amplify-dev add auth` steps. generated cognate resources in AWS had the desired fields.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-07 18:37 UTC, edwardfoyle requested changes

2021-06-07 18:37 UTC, edwardfoyle commented on packages/amplify-headless-interface/src/interface/auth/add.ts
> +  aliasAttributes?: CognitoUserAliasAttributes[];
you'll need to run `yarn generateSchemas --overwrite` in the headless-interface package to generate the JSON schema updates that go along with this change

2021-07-16 20:56 UTC, sachscode commented on packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
> +<% var autoVerifiedAttributes = props.autoVerifiedAttributes.concat(props.aliasAttributes).filter((attr, i, a) => ['email', 'phone_number'].includes(attr) && a.indexOf(attr) === i) %>
could you please rename 'a' as something more informative.

2021-07-16 21:05 UTC, sachscode commented on packages/amplify-category-auth/src/provider-utils/awscloudformation/service-walkthrough-types.ts
> +export type AliasAttributes = 'email' | 'phone_number' | 'preferred_username';
could you please use constants here instead of strings
 e.g ATTRIBUTE_TYPE.EMAIL/PHONE/PREFERRED_USERNAME

2021-07-16 21:14 UTC, sachscode requested changes
Changes look good, some minor questions.

2021-07-19 17:21 UTC, sachscode approved these changes
LGTM! 👍

2021-07-21 18:49 UTC, merged

2021-08-16 12:50 UTC, fabientownsend commented
Hello @johnpc and @sachscode! 


One of the issue that I come across since the change where `AliasAttributes` is used instead of `UsernameAttributes` when
following this Amplify documentation: https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js

The following error would be raised: "Username cannot be of email format, since user pool is configured for email alias"

Where a hash (uuid?) would be generated for the username with `UsernameAttributes` it is not the case when using `AliasAttributes`

I'm wondering if the cloud formation generated should have something like, if only one sign-in type selected, use `UserNameAttributes` otherwise use `AliasAttributes` which would have that kind of implementation:

`packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs`
``` javascript
<% if (props.aliasAttributes.length === 1 && props.aliasAttributes !== 'username') { %>
  UsernameAttributes: !Ref usernameAttributes
<% } else if (props.aliasAttributes && props.aliasAttributes.length > 1) { %>
  AliasAttributes: !Ref aliasAttributes
<% } %>
```

Note that in the current implementation the following could be deleted as `props.usernameAttributes` would always be set as undefined

``` javascript
<% if (props.usernameAttributes && props.usernameAttributes !== 'username') { %>
  UsernameAttributes: !Ref usernameAttributes
<% } %>
```

Another solution could be to hash the email is hashed when using `AliasAttributes` but as I'm unfamiliar with Amplify and AWS Cognito, I'm not sure where this should happen


Have a great one 👋

2021-09-02 15:55 UTC, benjamindoe commented
@fabientownsend, I'm running into the same bug you are. Do you think the maintainers might look at your comment if you opened it as a bug report in the issues area?

2021-12-15 12:07 UTC, jk171505 commented
Would be good to have the ability to edit this in the existing project.