fix(graphql-model-transformer): @model conflict resolution
aws-amplify/amplify-cli pull request #8035
Opened 2021-08-25 23:00 UTC by lazpavel

#### Description of changes
- implementation for graphql transformer V2 datastore resolvers

#### Description of how you validated changes
- added new tests
- ran `yarn test`
- manual testing by creating an app using `"useexperimentalpipelinedtransformer": true,`
- [circle ci](https://app.circleci.com/pipelines/github/lazpavel/amplify-cli/317/workflows/94594689-bad5-4bd2-8680-fb1df557b152)

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-30 16:28 UTC, lazpavel commented on packages/amplify-graphql-transformer-interfaces/src/transform-host-provider.ts
> +   * ServiceRole for the Amazon OpenSearch
this was the issue that we debugged with the appsync team, it looks that if we don't pass the serviceRole at the construction time, and assign one to the cfn object later, at the construction time one is created by default, this was causing the incorrect rights to write to the delta table. Will update the comment though

2021-08-30 17:09 UTC, lazpavel commented on packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
> +        ...(ctx.resolvers.isProjectUsingDataStore() ? { sync: toCamelCase(['sync', plurality(typeName, true)]) } : {}),
updated

2021-08-30 17:19 UTC, lazpavel commented on packages/amplify-graphql-transformer-core/src/transform-host.ts
> +import { DynamoDbDataSourceOptions } from '@aws-amplify/graphql-transformer-interfaces/src/transform-host-provider';
updated

2021-08-30 19:52 UTC, SwaySway approved these changes
aside from nits lgtm

2021-09-11 00:37 UTC, SwaySway requested changes
A few more comments on using datastore check.
Can we also update the flag in searchable to use the value if datastore is enabled?
https://github.com/aws-amplify/amplify-cli/blob/50f07efcf7c5663b6fd123d300ec473377d03abe/packages/amplify-graphql-searchable-transformer/src/graphql-searchable-transformer.ts#L80

2021-09-11 00:37 UTC, SwaySway commented on packages/amplify-graphql-transformer-core/src/config/transformer-config.ts
>    Optimistic = 'OPTIMISTIC_CONCURRENCY',
nit: Can you rename the enums to uppercase, since most of the other enums used in the cli are uppercased as well for consistency

2021-09-11 00:37 UTC, SwaySway commented on packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
> +      }
we should use the datastore check here if we can (note: the interfaces will need this function as well)
```suggestion
      if (ctx.isProjectUsingDataStore()) {
        this.options.SyncConfig = SyncUtils.getSyncConfig(ctx as TransformerContextProvider, def!.name.value);
        this.addModelSyncFields(ctx, type);
      }
```

2021-09-11 00:37 UTC, SwaySway commented on packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
> +          : undefined),
We add the function on all interfaces the context uses we won't need the type casting.

2021-09-11 00:37 UTC, SwaySway commented on packages/amplify-graphql-model-transformer/src/graphql-model-transformer.ts
> +      this.options.SyncConfig = SyncUtils.getSyncConfig(ctx as TransformerContextProvider, def!.name.value);
see comment below on using datastore check

2021-09-11 00:37 UTC, SwaySway commented on packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts
> +          if (syncConfig) {
use datastore check here as well
```suggestion
          if (ctx.isProjectUsingDataStore()) {
            const syncConfig = SyncUtils.getSyncConfig(context, this.typeName) as SyncConfig;
```

2021-09-21 18:40 UTC, cjihrig approved these changes

2021-09-21 20:32 UTC, merged