fix(amplify-category-function): allow user to update function without length validation
aws-amplify/amplify-cli pull request #8052
Opened 2021-08-27 14:31 UTC by danielleadams

#### Description of changes
When updating a function, removes to category length validation so that a user can remove all category access.

#### Issue #, if available
Fixes https://github.com/aws-amplify/amplify-cli/issues/8010

#### Description of how you validated changes
I tested this locally by duplicating the Issue steps, and it works as requested now. 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

2021-08-30 12:19 UTC, danielleadams commented
Upon discussion with product, this is a bugfix.

2021-08-30 18:58 UTC, attilah requested changes
Could you add an E2E test that:
- creates an API
- creates a Lambda
- adds permission to Lambda to access API
- push
- remove all permissions
- push
- verify pushed cfn file to not to have the access permissions between resources defined.

This way we will cannot have a regression around the full removal of permissions.

2021-09-17 20:36 UTC, danielleadams commented
@attilah this is ready for re-review. thanks!

2021-09-17 20:39 UTC, attilah approved these changes
Thanks for the test! LGTM!

2022-01-12 03:01 UTC, danielleadams commented
Moving to draft until I have time to fix the test in the rebase.

2022-02-04 20:32 UTC, sachscode approved these changes

2022-02-04 20:42 UTC, cjihrig approved these changes

2022-02-04 21:40 UTC, merged