Fix: graphql-transformer-migrator add modelgen flag after v2 migrate
aws-amplify/amplify-cli pull request #9565
Opened 2022-01-19 22:02 UTC by marcvberg

Fixes #9503

#### Description of changes
Sets the modelgen plugin flag on migration to true so that erroneous warnings are not thrown about missing connections

#### Issue #, if available

#### Description of how you validated changes
Ran a local migration

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-19 22:18 UTC, cjihrig approved these changes

2022-01-19 22:29 UTC, lazpavel approved these changes

2022-01-24 19:26 UTC, cjihrig requested changes
Since this PR has changed a good bit since it's original version, can you include some tests as well.

2022-01-24 19:26 UTC, cjihrig commented on packages/amplify-graphql-transformer-migrator/src/state-migrator.ts
> +  let cliJson = getCliJsonFile(env);
```suggestion
  const cliJson = getCliJsonFile(env);
```

2022-01-24 19:26 UTC, cjihrig commented on packages/amplify-graphql-transformer-migrator/src/state-migrator.ts
> +  let backupPath = path.join(backupLocation(resourceDir), 'cli.json');
```suggestion
  const backupPath = path.join(backupLocation(resourceDir), 'cli.json');
```

2022-01-24 19:26 UTC, cjihrig commented on packages/amplify-graphql-transformer-migrator/src/state-migrator.ts
> +  let backupPath = path.join(backupLocation(resourceDir), 'cli.json');
```suggestion
  const backupPath = path.join(backupLocation(resourceDir), 'cli.json');
```

2022-01-24 19:26 UTC, cjihrig commented on packages/amplify-graphql-transformer-migrator/src/state-migrator.ts
> +  let backupJson: $TSAny = JSONUtilities.readJson(backupPath);
```suggestion
  const backupJson: $TSAny = JSONUtilities.readJson(backupPath);
```

2022-01-24 19:26 UTC, cjihrig commented on packages/amplify-graphql-transformer-migrator/src/state-migrator.ts
> +  return cliJSON;
```suggestion
  return cliJSON ?? stateManager.getCLIJSON(projectPath);
```

2022-02-04 23:06 UTC, cjihrig approved these changes

2022-02-11 20:20 UTC, merged