fix: use paginated listComponents endpoint instead of exportComponents
aws-amplify/amplify-cli pull request #9591
Opened 2022-01-24 17:06 UTC by johnpc

#### Description of changes

This PR switches away from using `exportComponents` to pull ui components from Studio. For customers with a very large number of components, this method can blow up due to a lambda response size limit. 

Instead, the paginated `listComponents` endpoint is used in tandem with `getComponent` for each component returned.

#### Issue #, if available

n/a

#### Description of how you validated changes

- pulled components manually against sample project
- updated unit tests
- e2e test coverage still passes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-24 17:11 UTC, cwoolum reviewed
Left a few comments

2022-01-24 17:39 UTC, johnpc commented on packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts
> +      const hydratedComponentPromises = componentsBatch.entities.map(async component => {
five seems awfully low - is that throttle limit from the getComponents endpoint really that aggressive?

2022-01-24 20:58 UTC, cjihrig commented on packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts
> +import pLimit from 'p-limit'
Does this need to be added to a package.json file?

2022-03-17 18:36 UTC, jhockett approved these changes

2022-03-17 19:50 UTC, johnpc commented on packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts
> +const limit = pLimit(5);
agreed on the magic number vs constants 👍. For your info the number 5 came from this comment: https://github.com/aws-amplify/amplify-cli/pull/9591#discussion_r790975595

I find it to be uncomfortably low but I assume @cwoolum knows something I don't

2022-04-06 20:44 UTC, SwaySway requested changes
The UIBuilder sdk has support for pagination in `exportComponents` and `exportThemes` now. Can we switch over to using this method instead?

https://docs.aws.amazon.com/amplifyuibuilder/latest/APIReference/API_ExportComponents.html#API_ExportComponents_RequestSyntax

2022-04-12 15:08 UTC, johnpc commented
this is closed by https://github.com/aws-amplify/amplify-cli/pull/10190

2022-04-12 15:08 UTC, closed without merging