fix(graphql): allow iam private rule to access update mutation when authenticated by cognito
aws-amplify/amplify-cli pull request #9682
Opened 2022-02-03 04:44 UTC by sundersc

#### Description of changes

Allow `update` mutation to respect cognito authentication for IAM private rule.

#### Issue #, if available

Fixes https://github.com/aws-amplify/amplify-cli/issues/9502

#### Description of how you validated changes
- Manual test
- yarn test

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-03 15:36 UTC, danielleadams requested changes
Looks good - do you mind adding a test? You can add an assertion to this test: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-auth-transformer/src/__tests__/multi-auth.test.ts#L613 since the snapshots for update are already created.

2022-02-03 18:30 UTC, sundersc reviewed
@danielleadams - I just realized that there is no snapshot for this specific flow. I've added one, this will validate the VTL changes for update mutation.

2022-02-04 18:11 UTC, danielleadams approved these changes

2022-02-04 21:43 UTC, ammarkarachi approved these changes

2022-02-04 21:43 UTC, merged